links = {
    'instagram' :'https://www.instagram.com/{}',
    'facebook'  :'https://www.facebook.com/{}',
    'twitter'   :'https://www.twitter.com/{}',
    'youtube'   :'https://www.youtube.com/{}',
    'blogger'   :'https://{}.blogspot.com',
    'reddit'    :'https://www.reddit.com/user/{}',
    'pinterest' :'https://www.pinterest.com/{}',
    'github'    :'https://www.github.com/{}',
    'tumblr'    :'https://{}.tumblr.com',
    'flickr'    :'https://www.flickr.com/people/{}',
    'vimeo'     :'https://vimeo.com/{}',
    'soundcloud':'https://soundcloud.com/{}',
    'disqus'    :'https://disqus.com/{}',
    'medium'    :'https://medium.com/@{}',
    'devianart' :'https://{}.deviantart.com',
    'vk'        :'https://vk.com/{}',
    'about.me'  :'https://about.me/{}',
    'imgur'     :'https://imgur.com/user/{}',
    'slideshare':'https://slideshare.net/{}',
    'spotify'   :'https://open.spotify.com/user/{}',
    'scribd'    :'https://www.scribd.com/{}',
    'badoo'     :'https://www.badoo.com/en/{}',
    'patreon'   :'https://www.patreon.com/{}',
    'bitbucket' :'https://bitbucket.org/{}',
    'dailymotion':'https://www.dailymotion.com/{}',
    'etsy'      :'https://www.etsy.com/shop/{}',
    'cashme'    :'https://cash.me/{}',
    'behance'   :'https://www.behance.net/{}',
    'goodreads' :'https://www.goodreads.com/{}',
    'instructables':'https://www.instructables.com/member/{}',
    'keybase'   :'https://keybase.io/{}',
    'kongregate':'https://kongregate.com/accounts/{}',
    'livejournal':'https://{}.livejournal.com',
    'angellist' :'https://angel.co/{}',
    'last.fm'   :'https://last.fm/user/{}',
    'dribbble'  :'https://dribbble.com/{}',
    'codeacademy':'https://www.codecademy.com/{}',
    'gravatar'  :'https://en.gravatar.com/{}',
    'foursquare':'https://foursquare.com/{}',
    'gumroad'   :'https://www.gumroad.com/{}',
    'newgrounds':'https://{}.newgrounds.com',
    'wattpad'   :'https://www.wattpad.com/user/{}',
    'canva'     :'https://www.canva.com/{}',
    'creativemarket':'https://creativemarket.com/{}',
    'trakt'     :'https://www.trakt.tv/users/{}',
    '500px'     :'https://500px.com/{}',
    'buzzfeed'  :'https://buzzfeed.com/{}',
    'tripadvisor':'https://tripadvisor.com/members/{}',
    'hubpages'  :'https://{}.hubpages.com',
    'contently' :'https://{}.contently.com',
    'houzz'     :'https://houzz.com/user/{}',
    'blip.fm'   :'https://blip.fm/{}',
    'wikipedia' :'https://www.wikipedia.org/wiki/User:{}',
    'codementor':'https://www.codementor.io/{}',
    'reverbnation':'https://www.reverbnation.com/{}',
    'designspiration65':'https://www.designspiration.net/{}',
    'bandcamp'  :'https://www.bandcamp.com/{}',
    'colourlovers':'https://www.colourlovers.com/love/{}',
    'ifttt'     :'https://www.ifttt.com/p/{}',
    'slack'     :'https://{}.slack.com',
    'okcupid'   :'https://www.okcupid.com/profile/{}',
    'trip'      :'https://www.trip.skyscanner.com/user/{}',
    'ello'      :'https://ello.co/{}',
    'hackerone' :'https://hackerone.com/{}',
    'freelancer':'https://www.freelancer.com/u/{}'
}